### ISSUE TITLE
FlowLayout does not inherit layout direction.

### ISSUE THREAD

**Issue by DavidDTA** [ApmeM/android-flowlayout#53]
It should use its parent's layout direction and fall back to the locale.

**Comment by TonyHaddad91** [comment]
Hey @hospitalitarian have you solved this issue

**Comment by hospitalitarian** [comment]
No.  We set this manually on each `FlowLayout`.

**Comment by TonyHaddad91** [comment]
Hey Sorry but could u clarify your answer i have set the layoutDirection attribute to the flowlayout but with no luck

**Comment by hospitalitarian** [comment]
We are actually using version 1.9, and have code that looks like this:
```java
flowLayout.setLayoutDirection(mSourceLanguage.isRTL() ? View.LAYOUT_DIRECTION_RTL : View.LAYOUT_DIRECTION_LTR);

final int prevGravity = flowLayout.getGravity();
final int prevGravityVertical = prevGravity & Gravity.VERTICAL_GRAVITY_MASK;
final int prevGravityHorizontal = prevGravity & Gravity.HORIZONTAL_GRAVITY_MASK;
int newGravityHorizontal = prevGravityHorizontal;
if (prevGravityHorizontal != Gravity.CENTER_HORIZONTAL && prevGravityHorizontal != Gravity.FILL_HORIZONTAL) {
    newGravityHorizontal = mSourceLanguage.isRTL() ? Gravity.RIGHT : Gravity.LEFT;
}
flowLayout.setGravity(prevGravityVertical | newGravityHorizontal);
```

Note that `mSourceLanguage.isRTL()` is independent of the parent layout direction.

In order to set the language according to the parent, setting it at creation time may not be enough.  When views are first created, they don't have a direction set yet.  In order to pick up the direction once it is inferred, set the `FlowLayout`'s layout direction in the parent's `onRtlPropertiesChanged`.

**Comment by AlinAsghari** [comment]
i want to use flowLayout in RTL direction but its behavior in display items doesn't work fine.
i want to start add a button in right side and then add next button in left side of the first button and so on.
I'm so confused plz help me....

**Comment by Dev-iL** [comment]
@AlinAsghari I think this was [fixed long ago](https://github.com/Dev-iL/android-flowlayout/commit/0c7a8a02f7a9136c9934792c3d1f260a6cf11de7) on a different [fork](https://github.com/ApmeM/android-flowlayout/network)...

**Comment by ApmeM** [comment]
This pull request was merged into master branch.
